#!/usr/bin/env bash
# install load balancer
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 100.26.132.19:80 check\n\tserver server2 18.209.223.94:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
