#!/usr/bin/env bash
# install load balancer
apt-get -y update 
apt-get -y install haproxy=1.6.\*
echo '
frontend yasmineltair.tech
         bind 0:80
	 default_backend web_servers

backend web_servers
        balance roundrobin
	server 512743-web-01 100.26.132.19
	server 512743-web-02 18.209.223.94
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
