#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

rm /etc/nginx/sites_enabled/default
ln -s /etc/nginx/sites_available/default /etc/nginx/sites_enabled/default
service nginx restart
