#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

i=0
while [ $i -le 12 ]
do
   echo "Hour: $i"
   m=1
   while [ $m -lt 60 ]
   do
      echo $m
      m=$((m+1))
      done
i=$((i+1))
done
