#!/usr/bin/env bash
# make your fix short and sweet.
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -l apache2
chmod ugo+wrk /etc/apache2/ports.conf /etc/nginx/nginx.conf | sudo -u nginx service
